config/routes.rb
Noshare::Application.routes.draw do

  mount ResqueWeb::Engine => '/resque'

  devise_for :users

  root 'info#show'

  get '/app(/*path)', to: 'info#app'

  resources :photos do
    collection do
      get :new_bulk
      post :create_bulk
    end
    member do
      get :download
      post :remove_tag
    end
  end

  resources :tags

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  attr_accessor :new_tags

  THUMB_SIZE = 50
  MEDIUM_SIZE = 200
  LARGE_SIZE = 2048
  THUMB_TYPE = :jpg

  has_attached_file :file,
                    styles: {
                      thumb: ["#{THUMB_SIZE}x#{THUMB_SIZE}#", THUMB_TYPE],
                      medium: ["#{MEDIUM_SIZE}x#{MEDIUM_SIZE}#", :jpg],
                      large: ["#{LARGE_SIZE}x#{LARGE_SIZE}>", :jpg],
                      large_webp: ["#{LARGE_SIZE}x#{LARGE_SIZE}>", :webp],
                    },
                    convert_options: {
                      thumb: '-quality 90 -interlace Plane',
                      medium: '-quality 85 -interlace Plane',
                      large: '-quality 85',
                      large_webp: '-quality 85 -define webp:method=6',
                    },
                    default_url: '/images/:style/missing.png',
                    url: '/photos/:hash.:extension',
                    hash_secret: ENV['PHOTO_HASH_SECRET'],
                    # Strip EXIF data from scaled images
                    convert_options: { all: '-strip' }

  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :file
  process_in_background :file
  after_post_process :parse_exif
  after_post_process :update_couch

  acts_as_taggable


  # Parses EXIF data out of the photo and stores it in the database
  def parse_exif
    exif = EXIFR::JPEG.new(file.queued_for_write[:original].path)
    return if exif.nil? or not exif.exif?
    self.taken_at = exif.date_time
  rescue
    false
  end

  def update_couch
    return
    hash = photo_hash
    begin
      doc = couch.get(doc_id).body
      hash.merge!(_rev: doc['_rev'])
    rescue Faraday::Error::ResourceNotFound
    end
    couch.put(doc_id, hash)
  end

  def photo_hash
    hash = Rabl::Renderer.new('photos/index.json', self, :view_path => 'app/views', :format => 'hash').render
    hash.delete(:id)
    hash
  end

  def doc_id
    id.to_s
  end

  def couch
    @couch ||= Faraday.new(:url => 'http://127.0.0.1:5984/noshare_dev') do |conn|
      conn.request :json
      conn.response :json
      conn.response :logger                  # log requests to STDOUT
      conn.response :raise_error
      conn.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end
  end

  def thumb_data
    path = File.join(Rails.root, 'public', file.url(:thumb, false))
    data = Base64.strict_encode64(File.binread(path))
    "data:image/#{THUMB_TYPE};base64,#{data}"
  end

  def timestamp
    taken_at || created_at
  end

end

app/models/photo_observer.rb
class PhotoObserver < ActiveRecord::Observer

  observe :photo, ActsAsTaggableOn::Tagging

  def after_save(record)
    create_revision(record)
  end

  def after_destroy(record)
    create_revision(record)
  end

  def create_revision(record)
    Revision.create!(record_id: record.id, record_type: record.class.to_s)
  end

end

app/models/revision.rb
class Revision < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_action :authenticate_user!

end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  skip_before_action :authenticate_user!


  def show

  end

  def app
    
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :find_photo, only: [:show, :edit, :update, :remove_tag, :download, :destroy]


  def index
    respond_to do |format|
      format.html do
        @photos_by_month = (Photo.all.order(:taken_at)).group_by { |p| (p.taken_at || p.created_at).beginning_of_month }
      end
      format.json do
        # Use a transaction to ensure the revision doesn't change after we query the photos
        Photo.transaction do
          if params[:since]
            photo_ids = Revision.where('id > ?', Integer(params[:since])).where(record_type: 'Photo').pluck(:record_id)
            @photos = Photo.where(id: photo_ids)
            # Figure out which ids were deleted
            @deleted = photo_ids - @photos.map(&:id)
          else
            @deleted = []
            @photos = Photo.all
          end
          @revision = Revision.maximum(:id)
        end

        photo_list = @photos.map do |p|
          {
            id: p.id,
            taken_at: p.timestamp.to_i,
            thumb_data: p.thumb_data,
            thumb_url: p.file.url(:thumb, false),
            medium_url: p.file.url(:medium, false),
            large_url: p.file.url(:large, false),
            large_webp_url: p.file.url(:large_webp, false),
            url: p.file.url(:original, false),
            tags: p.tag_list,
            year: p.timestamp.year,
            month: p.timestamp.month,
            month_trunc: p.timestamp.beginning_of_month.to_i,

          }
        end

        photos_hash = {
          revision: @revision,
          photos: {
            deleted: @deleted,
            updated: photo_list
          }
        }

        render json: photos_hash
      end
    end
  end

  def new
    @photo = Photo.new
    render 'upload'
  end

  def create
    if params[:data_uri]
      @photo = Photo.new
      @photo.file = params[:data_uri]
    else
      @photo = Photo.new(photo_params)
    end
    if @photo.save!
      respond_to do |format|
        format.any { redirect_to photos_path }
        format.json do
          render json: {
            files: [
              {
                name: @photo.file_file_name,
                size: @photo.file_file_size,
                size: @photo.file.url,
                thumbnailUrl: @photo.file.url(:thumb),
                deleteUrl: photo_path(@photo),
                deleteType: 'DELETE',
              }
            ]
          }
        end
      end
    else
      render 'new'
    end
  end

  def new_bulk
  end

  def create_bulk
    processed = []
    failed = []
    params[:files].each do |f|
      begin
        Photo.create!(file: f)
        processed << f
      rescue => e
        logger.error e
        failed << f
      end
    end
    if failed.empty?
      flash[:notice] = "Added #{params[:files].size} photos."
    else
      flash[:alert] = "Added #{processed.size}. " +
                      "Failed to process the following files: #{failed.map(&:original_filename).join(', ')}"
    end
    redirect_to photos_path
  end

  def show
  end

  def edit
  end

  def update
    #@photo.tag_list.add(photo_params[:new_tags], parse: true)
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render 'edit'
    end
  end

  def remove_tag
    @photo.taggings.where(tag_id: params[:tag]).destroy_all
    redirect_to photo_path(@photo)
  end

  def download
    path = File.join(Rails.root, 'public', @photo.file.url(:original, timestamp: false))
    send_file path, disposition: 'attachment', filename: @photo.file_file_name
  end

  def destroy
    respond_to do |format|
      format.any { redirect_to photos_path }
      format.json do
        render json: {
          files: [
            {
              @photo.file_file_name => true
            }
          ]
        }
      end
    end
  end

private
  def find_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:file, :new_tags, :tag_list)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :find_tag, only: [:show]


  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @photos = Photo.tagged_with(@tag)
  end

  private
    def find_tag
      @tag = ActsAsTaggableOn::Tag.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/info/_photo_detail.html.haml
{{ var photo = it.photo; }}
.lightbox
  .photo
    %img{ src: '{{= it.host }}{{= photo.large_url }}' }

app/views/info/app.html.erb
<script>
    $(function() {
      window.noshareHost = <%= raw (ENV['NOSHARE_HOST'] || (request.protocol + request.host_with_port)).to_json %>;
      window.db = new PouchDB('photos');
      window.router = new Router();
      window.photosController = new PhotosController();
      window.imageCache = new Cache();
      imageCache.initialize().then(
        function() { console.log('yay!'); },
        function() { console.log('boo!'); }
      );
      router.go("/app");
      router.processStateChange();
    });
//    {{~photos :photo:index}}
//    <img class="photo-thumb" src="{{=photo.value.thumb_data}}" />
//    {{~}}
</script>

<div id="home" class="view"></div>
<script id="photosTemplate" type="text/doT">
<div class="container">
{{~it.keys :k:i}}
  {{ var photos = it.photos[k]; }}
  <div class="row" data-period="{{=k}}">
    <div class="col-md-12">
      <h1>
        {{=k}}
        &nbsp;
        <small>{{=photos.length}} photos</small>
      </h1>
      <div class="photo-section" data-year={{=k}}>
      </div>
    </div>
  </div>
{{~}}
</div>
<br />
<br />
</script>

<div id="photosZoom" class="view"></div>
<script id="photosZoomTemplate" type="text/doT">
<div class="container">
<div class="row" style="text-align: left" data-period="{{=it.period}}">
    <div class="col-md-12">
      <h1>
        {{=it.period}}
        &nbsp;
        <small>{{=it.photos.length}} photos</small>
      </h1>
      {{~it.photos :photo:index}}
        <img class="photo-medium" data-id="{{=photo._id}}" src="{{=photo.medium_url}}" />
      {{~}}
    </div>
  </div>
</div>
</script>

<div id="photoDetail" class="view"></div>
<script id="photoDetailTemplate" type="text/doT">
<%= render 'photo_detail' %>
</script>

app/views/info/show.html.slim
a.btn.btn-primary href=new_user_session_path Sign In
|&nbsp;&nbsp;
a.btn.btn-primary href=new_user_registration_path Register

app/views/layouts/_messages.html.haml
- if flash[:alert].present?
  .alert.alert-danger
    %a.close{ 'data-dismiss' => 'alert' } &#215;
    #flash_alert= flash[:alert]
- if flash[:notice].present?
  .alert.alert-success
    %a.close{ 'data-dismiss' => 'alert' } &#215;
    #flash_notice= flash[:notice]

app/views/layouts/_navigation.html.slim
nav.collapse.navbar-collapse.bs-navbar-collapse role="navigation"
  ul.nav.navbar-nav
    li = link_to 'Photos', photos_path
    li = link_to 'Upload', new_photo_path
    li = link_to 'Tags', tags_path
  ul.nav.navbar-nav.navbar-right
    - if user_signed_in?
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          = current_user.email
          b.caret
        ul.dropdown-menu
          li = link_to 'Logout', destroy_user_session_path, method: :delete
    - else
      li.navbar-right = link_to 'Login', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>

  <title>noshare</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
</head>

<body <% if params[:action] == 'app' %>data-no-turbolink<% end %>>

<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'noshare', root_path, class: 'navbar-brand' %>
    </div>
    <%= render 'layouts/navigation' %>
  </div>
</header>

<content>
  <div class="container">
    <%= render 'layouts/messages' %>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</content>

<footer>
  <br />
</footer>


</body>
</html>

app/views/photos/_thumb.html.slim
.photo.thumb.col-md-2.col-sm-3.col-xs-4
  a href=url_for(photo)
    img src=photo.file.url(:thumb)

app/views/photos/edit.html.slim
.row
  .col-md-12
    h1 Edit Photo
.row
  .col-md-12
    - # Form for adding additional tags
    = simple_form_for @photo do |f|
      = f.input :tag_list
      = f.submit class: 'btn btn-primary'

app/views/photos/index.html.haml
- @photos_by_month.each do |month,photos|
  .row{ style: 'text-align: left' }
    .col-md-12
      %h3
        = month.strftime('%B %Y')
        &nbsp;
        %small #{photos.count} photos
    .col-md-12
      - photos.each do |photo|
        = render 'thumb', photo: photo

app/views/photos/new.html.haml
%h1 New Photo

/Source:
/%select#videoSource
/%br
/%video#viewfinder{ autoplay: true }

/%h2 Upload
%img#photoUploadPreview
= simple_form_for @photo do |f|
  = f.input :file, accept: 'image/*', capture: true
  = hidden_field_tag 'data_uri'
  = f.submit class: 'btn btn-primary'

app/views/photos/new_bulk.haml
%h1 Bulk Upload

= simple_form_for :photo, url: create_bulk_photos_path, html: { method: :post, multipart: true } do |f|
  = file_field_tag 'files[]', multiple: true
  %br
  = f.submit 'Upload', class: 'btn btn-primary'

app/views/photos/show.html.haml
.row
  .col-md-12.text-left
    .buttons
      = link_to 'Edit', edit_photo_path(@photo), class: 'btn btn-default'
      = link_to 'Download', download_photo_path(@photo), class: 'btn btn-default'
    %h4.tags
      - @photo.tags.each do |tag|
        %a.label.label-primary{ href: tag_path(tag) }= tag

.row
  .col-md-12
    .photo
      %img{ src: @photo.file.url, style: 'cursor: pointer; max-height: 100%; max-width: 100%;' }

app/views/photos/upload.html.erb
<script>
$(function() {
  // Initialize the jQuery File Upload widget:
  $('#fileupload').fileupload({
    disableExif: true,
    disableImagePreview: true,
    paramName: 'photo[file]',
    url: '/photos'
  });
});
</script>

<div class="alert alert-info">
  Need to upload a lot of photos? Use the <%= link_to 'bulk upload tool', new_bulk_photos_path %>
</div>

<!-- The file upload form used as target for the file upload widget -->
<form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
  <!-- Redirect browsers with JavaScript disabled to the origin page -->
  <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  <div class="row fileupload-buttonbar">
    <div class="col-lg-7">
      <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
      <button type="submit" class="btn btn-primary start">
        <i class="glyphicon glyphicon-upload"></i>
        <span>Start upload</span>
      </button>
      <button type="reset" class="btn btn-warning cancel">
        <i class="glyphicon glyphicon-ban-circle"></i>
        <span>Cancel upload</span>
      </button>
      <button type="button" class="btn btn-danger delete">
        <i class="glyphicon glyphicon-trash"></i>
        <span>Delete</span>
      </button>
      <input type="checkbox" class="toggle">
      <!-- The global file processing state -->
      <span class="fileupload-process"></span>
    </div>
    <!-- The global progress state -->
    <div class="col-lg-5 fileupload-progress fade">
      <!-- The global progress bar -->
      <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
      </div>
      <!-- The extended global progress state -->
      <div class="progress-extended">&nbsp;</div>
    </div>
  </div>
  <!-- The table listing the files available for upload/download -->
  <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>